### PR TITLE
Convert all docstrings to numpy format

### PR DESCRIPTION
**Pull request by addisonlynch**
### Proposed changes in this pull request for fecon236

*In Progress*

* Converts all docstrings in source code (except tests) to numpy format 
   (https://numpydoc.readthedocs.io/en/latest/format.html).
* Adds ``test_formatting`` utility script to test both source code and docstring formatting

This will enable easy auto-documentation using ``sphinx-autodoc``.

- [x] Documentation change :memo:
- [x] Enhancement :art:

### Additional helpful details

- [x] REQUIRE: PR rebased on *latest* `develop` branch
- [x] This pull request needs to be manually tested
- [x] Work-in-progress: more changes will follow
- [x] Issue requires further discussion
- [ ] Issue has been fully resolved

ATTN mention: @rsvp

### CODE REVIEW

**Comment by rsvp** [comment]
### ***A truly magnificent gift*** over this holiday season!!

Thank you very much, @addisonlynch for your terrific and dedicated work! :1st_place_medal: 

**This is a monolithic revision** which covers every fecon236 module (23 of them, tests excluded) and function (though executable code is hopefully not affected) in terms of their docstring documentation :

```
$ git diff --name-status 10.8.0 pr_8
 A       bin/test_formatting
 M       fecon236/boots/bootstrap.py
 M       fecon236/dst/gaussmix.py
 M       fecon236/econ/infl.py
 M       fecon236/futures/cftc.py
 M       fecon236/host/_ex_Quandl.py
 M       fecon236/host/fred.py
 M       fecon236/host/hostess.py
 M       fecon236/host/qdl.py
 M       fecon236/host/stock.py
 M       fecon236/math/matrix.py
 M       fecon236/ml/learn.py
 M       fecon236/oc/optimize.py
 M       fecon236/parse/sec.py
 M       fecon236/prob/sim.py
 M       fecon236/prtf/boltzmann.py
 M       fecon236/rates/credit.py
 M       fecon236/rates/fedfunds.py
 M       fecon236/tool.py
 M       fecon236/top.py
 M       fecon236/tsa/holtwinters.py
 M       fecon236/util/group.py
 M       fecon236/util/system.py
 M       fecon236/visual/plots.py
```

I am double-checking every detail, and will merge after making some minor corrections. For example, old and new docstrings co-exist in function quarterly() in module ``fred.py``. *It will take some time to proof-read the entire repo, but it will get done.* 

Reference: for those of you not familiar with the **numpydoc** format, https://numpydoc.readthedocs.io/en/latest/format.html which is a derivative from the Google internal style.

**Comment by addisonlynch** [comment]
Sounds good @rsvp. I have a long list of notes and suggestions about the repo in general that I am still working on and will forward to you when completed (should be within the next week or so).

My memo focuses on repo clarity, defining the roles of and relationship between ``fecon235`` and ``fecon236``, and best practices for documentation moving forward. 

Once you've completed your review of these items, we should have a discussion about releasing an initial documentation site and what we would like to add in addition to the auto-documentation in both the short and long terms. Do review my changes here carefully, as though my work here has helped me to become acquainted with your code, I likely missed *many* items which should have been included in the docstrings. I'm sure there are quite a few in-line comments which could be pulled up to the docstrings, as well as parameters. I didn't add documentation for parameters which I was not in full understanding of.


I will send my memo over via email when it is complete. Dealing with finishing touches and semantics at the moment 😅

**Comment by rsvp** [comment]
### Double vs single back-ticks

I noticed double back-ticks being used where single ones are advised in the numpydoc guide: 

> [Use double back-ticks] \`\`monospace example\`\` ``monospace example`` if needed in any explanations. **Variable, module, function, and class names should be written between single back-ticks (\`numpy\` `numpy`).** --ibid.

The reStructuredText guide also advises using single back-ticks for "explicit descriptive markup like program identifiers." Whereas double back-ticks are to be used for monospaced text on a line. See http://docutils.sourceforge.net/docs/user/rst/quickref.html

The two types might render similarly under lucky circumstances, but the semantic treatment will differ among applications which may result in the appearance of unexpected fonts, or interfere with the creation of internal references (even an index) for the documentation.

Thoughts on abiding by the protocol? It would involve thousands of careful substitutions.

**Comment by rsvp** [comment]
@addisonlynch wrote:

>  I didn't add documentation for parameters which I was not in full understanding of.

Don't worry too much about that. Documenting the parameters is tedious, and makes the documentation in many cases unnecessarily verbose. 

On the other hand, ``Returns`` and ``Yields`` sections would be important for the user.

### "We should have a discussion..."

I think users and developers would appreciate an *open* discussion, so I would be happy to answer questions as part of an issue labeled as discussion at https://github.com/MathSci/fecon236/issues 

We could then use the discussion issues to write up a **FAQ document**.

**Comment by addisonlynch** [comment]
Hi @rsvp,

Do you have any initial thoughts on this? I am planning on continuing the documentation, and would love to hear any feedback you've come up with. Thanks!

**Comment by rsvp** [comment]
hi @addisonlynch, I've been on pause, waiting to hear from you regarding ***Double vs single back-ticks*** :-) as noted above.

Your pull request is monolithic, so conforming to the details of numpydoc is important. It's an all-or-nothing type of thing. Your commit messages were a bit vague and not particular to each module, so I would have to squash all commits into one, which would leave us in a partial state of correctness over hundreds of edits.

Perhaps take a directory of modules, one-by-one, as single PRs. But for the first PR, we should already have a web rendering prototype for testing, to check for syntax etc. What were your ideas for the documentation website?

Also, there were a number of fecon issues ("long list of notes and suggestions"), you wanted to discuss, but are those still forthcoming?

**Comment by addisonlynch** [comment]
I apologize. I should have scrolled up first. Not my best comment 😨 

For single vs double backticks, you are correct about the documentation and preferred use of single backticks for variables. I agree that it is best to adhere as closely as possible to the numpydoc standards. However, I've been digging further into this, and I'm having trouble understanding some of their documentation.

In refactoring ``fecon236``'s docstrings, I was (for the most part) working off of my experience with the ``pandas`` documentation. Though the pandas [docstring guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing_docstring.html#docstring) states that the numpydoc standard is followed, it seems that *double* backticks are used frequently in pandas docstrings ([example](https://github.com/pandas-dev/pandas/blob/master/pandas/core/algorithms.py)).

Taking a look at numpydoc's [own docstrings](https://github.com/numpy/numpydoc/blob/master/numpydoc/docscrape_sphinx.py), we see that double backticks are also often used to display inline code (be it variables, function/method names, etc). I wonder why this is the case given the snippet in your comment above...perhaps the disconnection in practice has to do with this section:

>  Often it’s possible to show equations as Python code or pseudo-code instead, which is much more readable in a terminal. For **inline display use double backticks** (like ``y = np.sin(x)``).

#### Thoughts

For downstream consequences:

> The two types might render similarly under lucky circumstances, but the semantic treatment will differ among applications which may result in the appearance of unexpected fonts, or interfere with the creation of internal references (even an index) for the documentation.

numpydoc is an extension of Sphinx, which renders text surrounded in double backticks as ``monospace``.  I believe that rendering using Sphinx (specifically ``sphinx-autodoc``) is the only circumstance under which the documentation should be generated and the docstrings parsed. Any downstream application which wishes to reference the docstrings would need to support Sphinx, given that it would not otherwise be able to handle Sphinx directives such as ``.. code-block:: python`` which are embedded within. 

I believe that the reason both numpydoc and ``pandas`` employ double backticks is likely to achieve the ``monospace`` result that Sphinx generates. Consider the difference below:

**Single Backticks**

image

**Double Backticks**

image

The second example is rendered in a manner consistent with how ``code`` is most often represented, including in the markup of this comment, which I do prefer.

**Comment by addisonlynch** [comment]
I can definitely rework this pull into one per directory or one per module. I've created a branch ``refactor-docstrings`` from which I will create branches for each module (i.e. ``bootstrap-docstrings``) and pulls for each into the ``refactor-docstrings`` branch. ``refactor-docstrings`` can serve as a staging area as modules are reviewed and finalized, and the entire refactor can be merged cleanly into ``develop`` once completed. Perhaps we can squash the module commits when merging into ``refactor-docstrings`` to create one clean commit message for each.

**Comment by addisonlynch** [comment]
Per @rsvp comment:

> But for the first PR, we should already have a web rendering prototype for testing, to check for syntax etc. What were your ideas for the documentation website?

I have an initial Sphinx documentation implementation in the fecon-docs [repository](https://github.com/addisonlynch/fecon-docs), which in part uses the ``sphinx-autodoc`` extension to render the docstrings ("auto-documentation"). There are also small sections which I have built out (such as [FRED Codes](https://github.com/addisonlynch/fecon-docs/blob/master/source/host/fred.rst)) for additional context. 

The repository is setup to use TravisCI with [doctr](https://github.com/drdoctr/doctr) for CI and CD to Github pages. The travis build lints the documentation source, though I do need to explore options for linting the docstrings themselves (there are a few, each of which have pros and cons).

The issue with setting up a dev environment for the docs is that each refactored module will be on a different branch. One option is to add a script to the travis build which pulls each module individually before installing ``fecon236`` to build and deploy the docs. After pushing any additional commits to the branches, simply re-running the Travis build (no push needed) would redeploy the docs.

For a local environment, I've included the Makefile rule ``livehtml`` which uses ``sphinx-autobuild`` ([docs](https://pypi.org/project/sphinx-autobuild/)) to serve the docs locally. 

I'll create a separate issue for discussion on the general structure of the documentation.

**Comment by rsvp** [comment]
## Single vs Double backticks

On the one hand, we will using ***reST*** syntax to render documentation via Sphinx. And on the other hand, your contrasting example shows how that syntax would render in a totally different mark-up language, ***Markdown*** (of the GitHub flavor, among many other variants): 

- which is why single backticks render as *italics*, not monospace per reST,
- yet using double backticks render as ``red monospace`` (whereas black might be preferable).

In other words,  are we to bend reST conventions to accommodate Markdown? Will the doc files have `.md` extensions? (No, `.rst`, I presume.) Is the issue how documentation will appear downstream using GitHub pages?

I just a bit worried about the indexing of terms (as opposed to code blocks) when regular expressions are used to parse documents. Also the Unix preference between two similar solutions is to choose that which requires less typing :-), so e.g. single backticks for variable names, which is in agreement with numpydocs.

## Let's rework this PR into one per module

That is how I rewrote fecon236 from fecon235, where a commit usually focused on a single module. The git history turns out to be very clear. 
 
## Tests

One should be able test the Sphinx implementation in fecon-docs independently of fecon236. Then the different Travis builds can be run independently. Also this would help to see rendering of the documentation, in progress, on a publicly accessible website.

## Third fecon236 branch

Yes, we can write documentation gradually as you described, then eventually merge with branches, develop and master.

**Comment by addisonlynch** [comment]
@rsvp Created separate pull requests for each module for review. Converted all double backticks to single backticks.

It's going to be a bit difficult have a live view of the *entire* documentation given that each module of the updated docstrings lives on a separate branch. As before, the shell for the new documentation is build in my [fecon-docs](https://github.com/addisonlynch/fecon-docs) repository. 

Auto-deployment of the documentation can commence once the documentation has access to all the properly formatted files (the old files will raise various sphinx errors that will not allow the documentation to build). See above comment for more info.

Let me know how you want to review all of this. I will open a separate issue for discussion and close this pull request.

**Pull request closed without merging**
